name: Publish

on:
  push:
  pull_request:

env:
  ROCKSPEC: postgrest-dev-1.rockspec

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      - uses: leafo/gh-actions-luarocks@v4
      - run: luarocks pack $ROCKSPEC
      - run: luarocks install lua-cjson
      - name: LuaRocks upload
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        env:
          LUA_ROCKS_API_KEY: ${{ secrets.LUA_ROCKS_API_KEY }}
        run: luarocks upload $ROCKSPEC --api-key=$LUA_ROCKS_API_KEY
