name: Unit tests

on:
  push:
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Install dependencies
        run: |
          make luarocks/dev
          luarocks make
      - name: Prepare database
        run: |
          make docker/compose/recreate
          # seen time where the DB wasn't fully ready
          sleep 1
          make docker/compose/psql/init
      - run: make test
      - run: make lint
      - run: make docker/compose/down
        if: always()
